export default {
  page: {
    backgroundColor: '#333944',
    display: 'flex',
    flex: 1,
    padding: '20px 0px',
    flexDirection: 'column',
  },
  closeIconWrapper: {
    position: 'absolute',
    top: 80,
    right: 10,
    padding: 10,
    fontSize: 25,
    color: 'white',
    cursor: 'pointer',
  },
  aboveRow: {
    borderBottom: '1px solid #3C4556',
    padding: '20px 50px',
  },
  rowContainer: {
    marginTop: '30px !important',
    padding: '0px 50px',
  },
  greyHeading: {
    fontFamily: "'roboto condensed',sans-serif",
    fontSize: 25,
    fontWeight: 500,
    color: '#556782',
    margin: '10px 0px',
  },
  greenHeading: {
    fontFamily: "'roboto condensed',sans-serif",
    fontSize: 25,
    fontWeight: 500,
    color: '#2CCFA0',
    margin: '10px 0px',
  },
  linksWrapper: {
    display: 'flex',
    flexDirection: 'column',
  },
  greyLink: {
    color: '#C4C4C4',
    fontFamily: "'montserrat',sans-serif",
    fontSize: 16,
    margin: '5px 0px',
    fontWeight: 300,
    cursor: 'pointer',
    display: 'inline-block',
  },
  whiteLink: {
    color: '#fff',
    fontFamily: "'montserrat',sans-serif",
    fontSize: 16,
    margin: '5px 0px',
    fontWeight: 300,
    cursor: 'pointer',
    display: 'inline-block',
  },
};
