export default (theme) => ({
  '@global': {
    '@page': {
      margin: '0px 5px',
      size: 'auto',
    },
  },
  content: {
    padding: '20px !important',
  },
  sendInvoiceButton: {
    width: 250,
    margin: '0px 10px',
  },
  daoLogo: {
    width: 250,
    height: 88,
    backgroundPosition: 'center',
    backgroundRepeat: 'no-repeat',
    backgroundSize: 'contain',
    backgroundColor: theme.palette.shadow.color1,
    borderRadius: 5,
  },
  invoiceTitleRightPart: {
    display: 'flex',
    alignItems: 'flex-end',
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  invoiceHeader: {
    backgroundColor: theme.palette.primary.color1,
    padding: 20,
  },
  invoiceNumber: {
    color: theme.palette.shadow.color1,
    fontFamily: theme.typography.font.family1,
    fontSize: 25,
    display: 'flex',
    alignItems: 'center',
  },
  invoiceName: {
    color: 'white',
    fontSize: 30,
    marginTop: 15,
    fontFamily: theme.typography.font.family1,
  },
  invoiceDateWrapper: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 20,
    backgroundColor: theme.palette.grey['100'],
  },
  invoiceDateBlock: {},
  invoiceDateLabel: {
    fontFamily: theme.typography.font.family2,
    fontSize: 16,
    color: theme.palette.grey['700'],
    marginBottom: 8,
  },
  invoiceDateValue: {
    fontFamily: theme.typography.font.family2,
    fontSize: 16,
    fontWeight: 'bold',
    color: theme.palette.grey['700'],
    marginBottom: 8,
  },
  invoiceDatePeriod: {
    fontFamily: theme.typography.font.family2,
    fontSize: 16,
    fontStyle: 'italic',
    color: theme.palette.grey['700'],
  },
  invoiceCustomer: {
    border: `1px solid ${theme.palette.grey['300']}`,
    borderTop: 0,
    padding: 20,
  },
  invoiceSectionTitle: {
    fontFamily: theme.typography.font.family2,
    fontSize: 16,
    color: theme.palette.blueGrey['50'],
    fontWeight: '500',
    marginBottom: 10,
  },
  invoiceTextValue: {
    fontFamily: theme.typography.font.family2,
    fontSize: 16,
    color: theme.palette.blueGrey['50'],
    fontWeight: '300',
    marginBottom: 7,
  },
  invoiceService: {
    border: `1px solid ${theme.palette.grey['300']}`,
    borderTop: 0,
    padding: 20,
  },
  gstLabel: {
    marginRight: 20,
  },
  gstCell: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  gstStatus: {
    fontSize: 13,
    fontFamily: theme.typography.font.family2,
    color: theme.palette.grey['400'],
  },
  gstHeaderCell: {
    width: '13%',
    padding: [[0, 10]],
  },
  smallTextCell: {
    fontSize: 14,
    padding: [[0, 10]],
  },
  bigWidthCell: {
    width: '80%',
    padding: [[0, 10]],
  },
  smallWidthCell: {
    width: '7%',
    padding: [[0, 10]],
  },
  mediumWidthCell: {
    width: '20%',
    padding: [[0, 10]],
  },
  borderCell: {
    paddingLeft: 10,
    paddingRight: 10,
    borderLeft: `1px solid ${theme.palette.grey['200']}`,
    minHeight: 50,
    display: 'flex',
    alignItems: 'center',
  },
  subtotalWrapper: {
    backgroundColor: theme.palette.grey['100'],
    padding: 15,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    border: `1px solid ${theme.palette.grey['300']}`,
    borderTop: 0,
  },
  subtotalText: {
    fontFamily: theme.typography.font.family2,
    fontSize: 16,
    color: theme.palette.grey['700'],
    fontWeight: '300',
  },
  balanceDueWrapper: {
    backgroundColor: theme.palette.primary.color1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 15,
  },
  balanceDueText: {
    fontFamily: theme.typography.font.family1,
    fontSize: 32,
    color: 'white',
    fontWeight: 'bold',
  },
  invoiceMessage: {
    border: `1px solid ${theme.palette.grey['300']}`,
    borderTop: 0,
    padding: 20,
  },
  invoiceAttachments: {
    border: `1px solid ${theme.palette.grey['300']}`,
    borderTop: 0,
    padding: 20,
  },
  invoiceAttachedFiles: {
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  payWrapper: {
    display: 'flex',
    alignItems: 'center',
  },
  payNowSection: {
    border: `1px solid ${theme.palette.grey['300']}`,
    borderTop: 0,
    padding: 20,
    alignSelf: 'stretch',
    display: 'flex',
    justifyContent: 'center',
    flexDirection: 'column',
  },
  payNowText: {
    fontFamily: theme.typography.font.family1,
    fontSize: 44,
    color: theme.palette.blueGrey['50'],
    fontWeight: 'bold',
    marginBottom: 10,
  },
  secureWrapper: {
    border: `1px solid ${theme.palette.grey['300']}`,
    borderTop: 0,
    padding: 20,
    display: 'flex',
    flex: 1,
    justifyContent: 'space-between',
  },
  secureBtns: {
    display: 'flex',
    alignItems: 'center',
  },
  secureBtn: {
    marginRight: 8,
    width: 180,
  },
  invoiceNote: {
    fontFamily: theme.typography.font.family1,
    fontSize: 16,
    color: theme.palette.blueGrey['50'],
    fontWeight: '500',
    margin: '20px 0px',
  },
});
